
target 'RxBarcodeScanner_Example' do
  platform :ios, '9.0'
  use_frameworks!

  pod 'BarcodeScanner'
  pod 'RxBarcodeScanner', :path => '../'

  target 'RxBarcodeScanner_Tests' do
    inherit! :search_paths

  end
end
