# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- xcodebuild clean build -workspace Example/RxBarcodeScanner.xcworkspace -scheme RxBarcodeScanner-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint
